# Generated by Django 4.2.1 on 2024-04-22 03:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MetroStation",
            fields=[
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "station_id",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "location",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=None,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=None,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "gtfs_stop_id",
                    models.CharField(
                        blank=True, default=None, max_length=16, null=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Metro Station",
                "verbose_name_plural": "Metro Stations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SystemParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Is ticketing enabled?"
                    ),
                ),
                (
                    "ticket_confirmation_timeout",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="Timeout for ticket confirmation (seconds)",
                    ),
                ),
                (
                    "repeat_ticketing_cooldown_period",
                    models.PositiveIntegerField(
                        default=5400,
                        help_text="Repeat ticketing cooldown period (seconds)",
                    ),
                ),
                (
                    "metro_stations_last_modified",
                    models.BigIntegerField(
                        default=1706689529,
                        help_text="Timestamp of last modification of Metro Stations data",
                    ),
                ),
                (
                    "qr_label_message",
                    models.TextField(
                        default="Scan this QR code at the entry gate booking",
                        help_text="HTML content for QR code label",
                    ),
                ),
                (
                    "max_passengers_per_ticket",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum number of passengers per ticket"
                    ),
                ),
                (
                    "report_to",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of emails to send reports to",
                        null=True,
                    ),
                ),
                (
                    "report_cc",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of emails to CC in reports",
                        null=True,
                    ),
                ),
                (
                    "service_enabled",
                    models.BooleanField(default=True, help_text="Is service enabled?"),
                ),
                (
                    "service_message",
                    models.TextField(
                        default="", help_text="Message to show when service is disabled"
                    ),
                ),
            ],
            options={
                "verbose_name": "System Parameter",
                "verbose_name_plural": "System Parameters",
            },
        ),
        migrations.CreateModel(
            name="FareMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("fare", models.FloatField(default=0.0)),
                (
                    "destination_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination_fares",
                        to="ondc_micromobility_api.metrostation",
                    ),
                ),
                (
                    "source_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_fares",
                        to="ondc_micromobility_api.metrostation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Fare Matrices",
                "unique_together": {("source_station", "destination_station")},
            },
        ),
    ]
