# Generated by Django 4.2.1 on 2023-09-18 09:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9A-Z_]*$",
                                "Only uppercase alphanumeric characters with underscore are allowed.",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentGatewayMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.paymentgateway",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentMode",
            fields=[
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9A-Z_]*$",
                                "Only uppercase alphanumeric characters with underscore are allowed.",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pending"), ("F", "Failed"), ("S", "Success")],
                        db_index=True,
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "transaction_type",
                    models.IntegerField(
                        choices=[(-1, "Debit"), (1, "Credit")],
                        db_index=True,
                        default=-1,
                    ),
                ),
                (
                    "gateway_order_id",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(blank=True, max_length=63, null=True),
                ),
                (
                    "gateway_transaction_status",
                    models.CharField(
                        choices=[("P", "Pending"), ("F", "Failed"), ("S", "Success")],
                        db_index=True,
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "gateway_mode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.paymentgatewaymode",
                    ),
                ),
                (
                    "original_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refund_transactions",
                        to="payments.transaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="paymentgatewaymode",
            name="mode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="payments.paymentmode"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentgatewaymode",
            unique_together={("gateway", "mode")},
        ),
    ]
