stops_data=[
    {
        "route_id": 10,
        "route_name": "993DOWN",
        "stops": [
            {"stop_name": "West Enclave / Sansad Vihar (T)", "code": "WEST_ENCLAVE_SANSAD_VIHAR_T"},
            {"stop_name": "Mangol Puri B Block (ORR)", "code": "MANGOL_PURI_B_BLOCK_ORR"},
            {"stop_name": "Peera Garhi Chowk", "code": "PEERA_GARHI_CHOWK"},
            {"stop_name": "Paschim Vihar (Super market)", "code": "PASCHIM_VIHAR_SUPER_MARKET"},
            {"stop_name": "Multan Nagar", "code": "MULTAN_NAGAR"},
            {"stop_name": "New Multan Nagar", "code": "NEW_MULTAN_NAGAR"},
            {"stop_name": "Ordinance Depot", "code": "ORDINANCE_DEPOT"},
            {"stop_name": "Madipur JJ Colony", "code": "MADIPUR_JJ_COLONY"},
            {"stop_name": "Madipur Village", "code": "MADIPUR_VILLAGE"},
            {"stop_name": "SPM College", "code": "SPM_COLLEGE"},
            {"stop_name": "Shivaji Park", "code": "SHIVAJI_PARK"},
            {"stop_name": "Maharaja Agrasen Hospital", "code": "MAHARAJA_AGRASEN_HOSPITAL"},
            {"stop_name": "Punjabi Bagh Terminal (Rohtak Road)", "code": "PUNJABI_BAGH_TERMINAL_ROHTAK_ROAD"},
            {"stop_name": "Punjabi Bagh West Power House", "code": "PUNJABI_BAGH_WEST_POWER_HOUSE"},
            {"stop_name": "Ram Pura", "code": "RAM_PURA"},
            {"stop_name": "Ashok Park", "code": "ASHOK_PARK"},
            {"stop_name": "Zakhira Flyover", "code": "ZAKHIRA_FLYOVER"},
            {"stop_name": "Daya Basti Flyover", "code": "DAYA_BASTI_FLYOVER"},
            {"stop_name": "Anand Parbat Industrial Area", "code": "ANAND_PARBAT_INDUSTRIAL_AREA"},
            {"stop_name": "Sarai Rohilla Govt Qtrs (Rohtak Road)", "code": "SARAI_ROHILLA_GOVT_QTRS_ROHTAK_ROAD"},
            {"stop_name": "Liberty Cinema", "code": "LIBERTY_CINEMA"},
            {"stop_name": "Dev Nagar", "code": "DEV_NAGAR"},
            {"stop_name": "Dev Nagar / Khalsa College", "code": "DEV_NAGAR_KHALSA_COLLEGE"},
            {"stop_name": "Prahlad Market", "code": "PRAHLAD_MARKET"},
            {"stop_name": "Thana DB Gupta Road", "code": "THANA_DB_GUPTA_ROAD"},
            {"stop_name": "DB Gupta Market", "code": "DB_GUPTA_MARKET"},
            {"stop_name": "Faiz Road", "code": "FAIZ_ROAD"},
            {"stop_name": "Karol Bagh Terminal", "code": "KAROL_BAGH_TERMINAL"},
            {"stop_name": "Jhandewalan", "code": "JHANDEWALAN"},
            {"stop_name": "Paharganj Police Station", "code": "PAHARGANJ_POLICE_STATION"},
            {"stop_name": "Chitra Gupta Road", "code": "CHITRA_GUPTA_ROAD"},
            {"stop_name": "Kalawati Hospital", "code": "KALAWATI_HOSPITAL"},
            {"stop_name": "Sucheta Kriplani Hospital", "code": "SUCHETA_KRIPLANI_HOSPITAL"},
            {"stop_name": "Super Bazar", "code": "SUPER_BAZAR"},
            {"stop_name": "Statesman House", "code": "STATESMAN_HOUSE"},
            {"stop_name": "Barakhamba Metro Station", "code": "BARAKHAMBA_METRO_STATION"},
            {"stop_name": "Modern School", "code": "MODERN_SCHOOL"},
            {"stop_name": "Mandi House", "code": "MANDI_HOUSE"},
            {"stop_name": "Tilak Bridge", "code": "TILAK_BRIDGE"},
            {"stop_name": "ITO", "code": "ITO"},
            {"stop_name": "Delhi Sectt", "code": "DELHI_SECTT"},
            {"stop_name": "Delhi Sachivalaya (Rajghat Power House)", "code": "DELHI_SACHIVALAYA_RAJGHAT_POWER_HOUSE"}
        ]
    },
    {
        "route_id": 1,
        "route_name": "102STLDOWN",
        "stops": [
            {"stop_name": "Rohini Sec 22 Terminal", "code": "ROHINI_SEC_22_TERMINAL"},
            {"stop_name": "Aggarsain Hospital (Rohini Sec 22)", "code": "AGGARSAIN_HOSPITAL_ROHINI_SEC_22"},
            {"stop_name": "Rohini Sec-21", "code": "ROHINI_SEC_21"},
            {"stop_name": "Pooth Kalan", "code": "POOTH_KALAN"},
            {"stop_name": "Brahm Shakti Hospital", "code": "BRAHM_SHAKTI_HOSPITAL"},
            {"stop_name": "Buddh Vihar", "code": "BUDDH_VIHAR"},
            {"stop_name": "Krishna Vihar", "code": "KRISHNA_VIHAR"},
            {"stop_name": "Mangol Puri Y Block", "code": "MANGOL_PURI_Y_BLOCK"},
            {"stop_name": "Mangol Pur Khurd", "code": "MANGOL_PUR_KHURD"},
            {"stop_name": "Avantika Xing", "code": "AVANTIKA_XING"},
            {"stop_name": "Mangolpur Kalan Village", "code": "MANGOLPUR_KALAN_VILLAGE"},
            {"stop_name": "Mangol Pur School (Kanjhawla Road)", "code": "MANGOL_PUR_SCHOOL_KANJHAWLA_ROAD"},
            {"stop_name": "Mangol Puri B Block (ORR)", "code": "MANGOL_PURI_B_BLOCK_ORR"},
            {"stop_name": "Peera Garhi Metro Station", "code": "PEERA_GARHI_METRO_STATION"},
            {"stop_name": "Udyog Nagar", "code": "UDYOG_NAGAR"},
            {"stop_name": "Inder Enclave", "code": "INDER_ENCLAVE"},
            {"stop_name": "Jwala Puri / Nangloi Depot", "code": "JWALA_PURI_NANGLOI_DEPOT"},
            {"stop_name": "Surajmal Stadium", "code": "SURAJMAL_STADIUM"},
            {"stop_name": "Sultanpuri Crossing", "code": "SULTANPURI_CROSSING"},
            {"stop_name": "Nangloi (Najafgarh Road)", "code": "NANGLOI_NAJAFGARH_ROAD"},
            {"stop_name": "Nangloi Metro Station", "code": "NANGLOI_METRO_STATION"},
            {"stop_name": "Nangloi JJ Colony Lokesh Cinema", "code": "NANGLOI_JJ_COLONY_LOKESH_CINEMA"},
            {"stop_name": "Qamruddin Nagar Terminal", "code": "QAMRUDDIN_NAGAR_TERMINAL"},
            {"stop_name": "Rajdhani Park", "code": "RAJDHANI_PARK"},
            {"stop_name": "Swarn Park", "code": "SWARN_PARK"},
            {"stop_name": "Mundka Village Crossing", "code": "MUNDKA_VILLAGE_CROSSING"},
            {"stop_name": "Mundka Village Metro Station", "code": "MUNDKA_VILLAGE_METRO_STATION"},
            {"stop_name": "Mundka School (Rani Khera Road)", "code": "MUNDKA_SCHOOL_RANI_KHERA_ROAD"},
            {"stop_name": "Friends Enclave Mundka", "code": "FRIENDS_ENCLAVE_MUNDKA"},
            {"stop_name": "Mundka Railway Station", "code": "MUNDKA_RAILWAY_STATION"},
            {"stop_name": "Rani Khera Depot Crossing", "code": "RANI_KHERA_DEPOT_CROSSING"},
            {"stop_name": "Rani Khera Depot III", "code": "RANI_KHERA_DEPOT_III"}
        ]
    }
]
