# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Docker.gitlab-ci.yml

# Build a Docker image with CI/CD and push to the GitLab registry.
# Docker-in-Docker documentation: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
#
# This template uses one generic job with conditional builds
# for the default branch and all other (MR) branches.

# TODO: add test: call healthcheck end point
variables:
  AWS_REGION: "ap-south-1"
  AWS_ACCOUNT_ID: 178761578367
  ECR_REPO_URL: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
  ECR_IMAGE_URL: "${ECR_REPO_URL}/chartr-ondc-delhi-buses-buyer"
  OIDC_IAM_ROLE: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/gitlab-pipelines"

docker-build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  services:
    - docker:dind
  before_script:
    - apk add --no-cache aws-cli
    - >
      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
      $(aws sts assume-role-with-web-identity
      --role-arn ${OIDC_IAM_ROLE}
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token ${GITLAB_OIDC_TOKEN}
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
    - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REPO_URL}
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

  script:
    - |
      tag=":$CI_COMMIT_REF_SLUG"
    - docker buildx version
    - docker buildx create --use
    # Pull the cache first. If it doesn't exist, continue without failing the pipeline.
    - docker pull --platform linux/arm64/v8 $CI_REGISTRY_IMAGE${tag}-cache || true
    # Use cache-from to utilize the previously pulled cache and cache-to to push new cache layers.
    - docker buildx build --push --cache-to $CI_REGISTRY_IMAGE${tag}-cache --cache-from $CI_REGISTRY_IMAGE${tag}-cache --platform linux/arm64/v8 --pull -t "$ECR_IMAGE_URL${tag}" .
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH == "production" || $CI_COMMIT_BRANCH == "staging"
      exists:
        - Dockerfile
