# Generated by Django 4.2.1 on 2023-09-18 09:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransitOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                (
                    "transit_mode",
                    models.IntegerField(
                        choices=[
                            (1, "Bike"),
                            (3, "Car"),
                            (5, "Bus"),
                            (7, "Train"),
                            (9, "Tram"),
                            (11, "Metro"),
                            (13, "Ferry"),
                            (15, "Scooter"),
                            (17, "Auto Rickshaw"),
                            (19, "Manual Rickshaw"),
                            (21, "Airplane"),
                        ],
                        help_text="Type of transit option, like bike, bus, metro etc.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Transit Options",
            },
        ),
        migrations.CreateModel(
            name="TransitProvider",
            fields=[
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the transit agency or service, like Uber, MTA, Rapido, American Airlines etc. Accepts only alphanumeric characters and spaces",
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-zA-Z\\-_ ]*$",
                                "Only alphanumeric characters are allowed.",
                            )
                        ],
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("logo_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Transit Providers",
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "transit_mode",
                    models.IntegerField(
                        choices=[
                            (1, "Bike"),
                            (3, "Car"),
                            (5, "Bus"),
                            (7, "Train"),
                            (9, "Tram"),
                            (11, "Metro"),
                            (13, "Ferry"),
                            (15, "Scooter"),
                            (17, "Auto Rickshaw"),
                            (19, "Manual Rickshaw"),
                            (21, "Airplane"),
                        ],
                        help_text="Type of transit option, like bike, bus, metro etc.",
                    ),
                ),
                (
                    "start_location_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "start_location_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "start_location_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "start_location_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "end_location_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "end_location_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "end_location_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "end_location_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scheduled_start_datetime",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "scheduled_end_datetime",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "actual_start_datetime",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "actual_end_datetime",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("duration", models.IntegerField(blank=True, default=-1, null=True)),
                ("distance", models.IntegerField(blank=True, default=-1, null=True)),
                ("fare", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trips",
                        to="transit.trip",
                    ),
                ),
                (
                    "transit_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transit.transitoption",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Trips",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="transitoption",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transit_options",
                to="transit.transitprovider",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transitoption",
            unique_together={("provider", "transit_mode")},
        ),
    ]
