# Generated by Django 4.2.1 on 2023-10-29 03:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("transit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "start_datetime",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="DateTime when the service exception starts",
                        null=True,
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="DateTime when the service exception ends",
                        null=True,
                    ),
                ),
                (
                    "exception_type",
                    models.IntegerField(
                        choices=[
                            (1, "Service Added"),
                            (2, "Service Removed"),
                            (3, "Service Updated"),
                        ]
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Calendar Dates",
            },
        ),
        migrations.CreateModel(
            name="ServiceCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monday",
                    models.BooleanField(
                        default=True, help_text="This service enabled on Monday"
                    ),
                ),
                (
                    "tuesday",
                    models.BooleanField(
                        default=True, help_text="This service enabled on Tuesday"
                    ),
                ),
                (
                    "wednesday",
                    models.BooleanField(
                        default=True, help_text="This service enabled on Wednesday"
                    ),
                ),
                (
                    "thursday",
                    models.BooleanField(
                        default=True, help_text="This service enabled on Thursday"
                    ),
                ),
                (
                    "friday",
                    models.BooleanField(
                        default=True, help_text="This service enabled on Friday"
                    ),
                ),
                (
                    "saturday",
                    models.BooleanField(
                        default=True, help_text="This service enabled on Saturday"
                    ),
                ),
                (
                    "sunday",
                    models.BooleanField(
                        default=True, help_text="This service enabled on Sunday"
                    ),
                ),
                (
                    "monday_start_time",
                    models.TimeField(
                        default=datetime.time(0, 0),
                        help_text="Time when this service starts on Monday morning",
                    ),
                ),
                (
                    "monday_end_time",
                    models.TimeField(
                        default=datetime.time(23, 59),
                        help_text="Time when this service ends on Monday night",
                    ),
                ),
                (
                    "tuesday_start_time",
                    models.TimeField(
                        default=datetime.time(0, 0),
                        help_text="Time when this service starts on Tuesday morning",
                    ),
                ),
                (
                    "tuesday_end_time",
                    models.TimeField(
                        default=datetime.time(23, 59),
                        help_text="Time when this service ends on Tuesday night",
                    ),
                ),
                (
                    "wednesday_start_time",
                    models.TimeField(
                        default=datetime.time(0, 0),
                        help_text="Time when this service starts on Wednesday morning",
                    ),
                ),
                (
                    "wednesday_end_time",
                    models.TimeField(
                        default=datetime.time(23, 59),
                        help_text="Time when this service ends on Wednesday night",
                    ),
                ),
                (
                    "thursday_start_time",
                    models.TimeField(
                        default=datetime.time(0, 0),
                        help_text="Time when this service starts on Thursday morning",
                    ),
                ),
                (
                    "thursday_end_time",
                    models.TimeField(
                        default=datetime.time(23, 59),
                        help_text="Time when this service ends on Thursday night",
                    ),
                ),
                (
                    "friday_start_time",
                    models.TimeField(
                        default=datetime.time(0, 0),
                        help_text="Time when this service starts on Friday morning",
                    ),
                ),
                (
                    "friday_end_time",
                    models.TimeField(
                        default=datetime.time(23, 59),
                        help_text="Time when this service ends on Friday night",
                    ),
                ),
                (
                    "saturday_start_time",
                    models.TimeField(
                        default=datetime.time(0, 0),
                        help_text="Time when this service starts on Saturday morning",
                    ),
                ),
                (
                    "saturday_end_time",
                    models.TimeField(
                        default=datetime.time(23, 59),
                        help_text="Time when this service ends on Saturday night",
                    ),
                ),
                (
                    "sunday_start_time",
                    models.TimeField(
                        default=datetime.time(0, 0),
                        help_text="Time when this service starts on Sunday morning",
                    ),
                ),
                (
                    "sunday_end_time",
                    models.TimeField(
                        default=datetime.time(23, 59),
                        help_text="Time when this service ends on Sunday night",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        db_index=True,
                        default=datetime.date(2000, 1, 1),
                        help_text="Start date of this service",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        db_index=True,
                        default=datetime.date(2075, 12, 31),
                        help_text="End date of this service",
                    ),
                ),
                (
                    "transit_option",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_calendar",
                        to="transit.transitoption",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Service Calendars",
            },
        ),
    ]
