# Generated by Django 4.2.1 on 2023-11-15 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="systemparameters",
            options={
                "verbose_name": "System Parameter",
                "verbose_name_plural": "System Parameters",
            },
        ),
    ]
