# Generated by Django 4.2.1 on 2023-09-18 09:11

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("display_name", models.CharField(max_length=200)),
                (
                    "country",
                    django_countries.fields.CountryField(default="IN", max_length=2),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
                "ordering": ("display_name",),
                "unique_together": {("code", "country")},
            },
        ),
    ]
