# Generated by Django 4.2.1 on 2023-10-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="is_visible",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
