# Generated by Django 4.2.1 on 2023-09-18 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Journey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Initiated"),
                            (3, "In Progress"),
                            (5, "Completed"),
                            (6, "Cancelled"),
                        ],
                        db_index=True,
                        default=1,
                        help_text="Type of journey status like Initiated, In Progress, Completed, Cancelled",
                    ),
                ),
                ("start_datetime", models.DateTimeField(blank=True, null=True)),
                ("end_datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by_journey",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_for",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_for_journey",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tickets",
                    models.ManyToManyField(
                        blank=True,
                        db_index=True,
                        related_name="journeys",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Journeys",
                "ordering": ("-created_at",),
            },
        ),
    ]
