# Generated by Django 4.2.1 on 2023-09-18 09:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modules.pnr_generator
import phonenumber_field.modelfields
import tickets.models.ticket_setup


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("transit", "0001_initial"),
        ("payments", "0001_initial"),
        ("coupons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FareBreakup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basic",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "toll",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "convenience_charge",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "convenience_charge_tax",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        help_text="Please enter calculated value.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "discount",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "add_on",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "add_on_tax",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        help_text="Please enter calculated value.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cancellation_chg",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "franchisee_service_charge",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "amount",
                    models.FloatField(
                        db_index=True,
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "coupon_discount",
                    models.FloatField(
                        db_index=True,
                        default=0.0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="coupons.coupon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "start_location_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "start_location_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "start_location_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "start_location_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "end_location_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "end_location_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "end_location_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "end_location_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "pnr",
                    models.CharField(
                        db_index=True,
                        default=modules.pnr_generator.generate_pnr,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Confirmed"),
                            (3, "Pending"),
                            (5, "Cancelled"),
                            (7, "Expired"),
                        ],
                        db_index=True,
                        default=3,
                        help_text="Type of transit option, like bike, bus, metro etc.",
                    ),
                ),
                ("transit_pnr", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "seat_no",
                    models.CharField(blank=True, default=None, max_length=5, null=True),
                ),
                ("amount", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "payment_type",
                    models.IntegerField(
                        choices=[(1, "Prepaid"), (3, "Postpaid"), (5, "Free")],
                        db_index=True,
                        default=1,
                        help_text="Type of payment, PREPAID/POSTPAID/FREE",
                    ),
                ),
                (
                    "payment_status",
                    models.IntegerField(
                        choices=[(1, "Not Completed"), (3, "Completed")],
                        db_index=True,
                        default=1,
                        help_text="1/3",
                    ),
                ),
                ("valid_till", models.DateTimeField(blank=True, null=True)),
                (
                    "poc_name",
                    models.CharField(
                        blank=True,
                        help_text="This would be PoC for any ticket",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "poc_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="This would be PoC for any ticket",
                        max_length=128,
                        null=True,
                        region=None,
                    ),
                ),
                ("driver_name", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "driver_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "conductor_name",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                (
                    "conductor_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "vehicle_number",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "vehicle_description",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("terminal", models.CharField(blank=True, max_length=10, null=True)),
                ("service_details", models.JSONField(blank=True, null=True)),
                (
                    "journey_leg_index",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_by_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_for",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_for_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fare",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tickets.farebreakup",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tickets",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=40, unique=True)),
                (
                    "discount_percentage",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("is_description_required", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
            ],
            options={
                "verbose_name": "Ticket Type",
                "verbose_name_plural": "Ticket Types",
            },
        ),
        migrations.CreateModel(
            name="TicketUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("trigger_signal", models.BooleanField(default=True)),
                ("details", models.JSONField(blank=True, null=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_updates",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Update",
                "verbose_name_plural": "Ticket Updates",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_type",
            field=models.ForeignKey(
                default=tickets.models.ticket_setup.TicketType.get_default_pk,
                on_delete=django.db.models.deletion.PROTECT,
                to="tickets.tickettype",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="transaction",
            field=models.ManyToManyField(
                blank=True, related_name="tickets", to="payments.transaction"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="transit_option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="transit.transitoption"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("transit_option", "pnr")},
        ),
    ]
