# Generated by Django 4.2.1 on 2023-11-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="end_location_lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0.0, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="end_location_lng",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0.0, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="start_location_lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0.0, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="start_location_lng",
            field=models.DecimalField(
                blank=True, decimal_places=6, default=0.0, max_digits=9, null=True
            ),
        ),
    ]
