# Generated by Django 4.2.1 on 2023-11-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_alter_ticket_end_location_lat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="passenger_count",
            field=models.IntegerField(
                default=1, help_text="Number of passengers for this ticket"
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat_no",
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
