# Generated by Django 4.2.1 on 2023-11-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_ticket_passenger_count_alter_ticket_seat_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="transit_pnr",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
