# Generated by Django 4.2.1 on 2024-01-04 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transit", "0003_alter_trip_end_location_lat_and_more"),
        ("tickets", "0005_alter_ticket_passenger_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "start_location_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "start_location_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "start_location_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0.0,
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "start_location_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0.0,
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "end_location_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "end_location_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "end_location_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0.0,
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "end_location_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        default=0.0,
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        db_index=True,
                        default=0.0,
                        help_text="Ranking or weightage for the recommendation",
                    ),
                ),
                (
                    "created_for",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_for_ticket_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transit_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_recommendation_transit_options",
                        to="transit.transitoption",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
