# Generated by Django 4.2.1 on 2024-04-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0006_ticketrecommendation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="end_location_code",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="start_location_code",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="ticketrecommendation",
            name="end_location_code",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name="ticketrecommendation",
            name="start_location_code",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
