# Generated by Django 4.2.1 on 2024-06-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0007_alter_ticket_end_location_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="farebreakup",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
