# Generated by Django 4.2.1 on 2024-08-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0008_farebreakup_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="ride_otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
