# Generated by Django 4.2.1 on 2024-08-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0009_ticket_ride_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
